spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

oauth:
  github:
    client-id: Ov23li13h2e0fXX4Ivzd
    client-secret: ${GITHUB_SECRET}
  kakao:
    client-id: 636379da8a0126dd5bed25977e8cdafb
    client-secret: ${KAKAO_SECRET}
