spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123!@#

oauth:
  github:
    client-id: Ov23li13h2e0fXX4Ivzd
    client-secret: ${GITHUB_SECRET}
  kakao:
    client-id: 636379da8a0126dd5bed25977e8cdafb
    client-secret: ${KAKAO_SECRET}
  google:
    client-id: 528956748173-0q3lhssavils8fadlbgd65sbnphqff49.apps.googleusercontent.com
    client-secret: ${GOOGLE_SECRET}
    redirect-uri: http://localhost:8080/google.html

jwt:
  secret-key: random-secret-key-32-byte-1234567890-1234567890
  access-exp: 3600000
  refresh-exp: 86400000

rabbitmq:
  exchange:
    name: code.execution.exchange
  routing:
    key: code.execution.key